[package]
name = "update-alternatives"
version = "0.6.0"
authors = ["gregjm@umich.edu", "git@fthomys.me"]

[dependencies]
clap = { version = "4.5.54", features = ["cargo"] }
nix = { version = "0.30.1", features = ["user"] }
serde_derive = "1.0.228"
serde_json = "1.0.149"
